/**
 * Central Bridge Configuration for VERDA (وِردا) Clinic Landing Page
 * Template #3 in the Picksaw Studio clinic template collection
 * 
 * NOTE:
 * - For images & media: Edit `src/config/images.config.ts`
 * - For texts & content: Edit `src/config/content.config.ts`
 */

import { IMAGES_CONFIG } from './images.config';
import { CONTENT_CONFIG } from './content.config';

export { IMAGES_CONFIG } from './images.config';
export { CONTENT_CONFIG } from './content.config';

export const CLINIC_CONFIG = {
  // Brand Identity
  CLINIC_NAME: CONTENT_CONFIG.BRAND.CLINIC_NAME,
  CLINIC_NAME_EN: CONTENT_CONFIG.BRAND.CLINIC_NAME_EN,
  CLINIC_TAGLINE: CONTENT_CONFIG.BRAND.TAGLINE,
  CLINIC_CATEGORY: CONTENT_CONFIG.BRAND.CATEGORY,
  CLINIC_SUBTITLE: CONTENT_CONFIG.BRAND.SUBTITLE,
  CLINIC_DESCRIPTION: CONTENT_CONFIG.BRAND.DESCRIPTION,

  // Doctor / Team Information
  DOCTOR_NAME: CONTENT_CONFIG.DOCTOR.NAME,
  DOCTOR_TITLE: CONTENT_CONFIG.DOCTOR.TITLE_EN,
  DOCTOR_BIO: CONTENT_CONFIG.DOCTOR.BIO,
  DOCTOR_IMAGE: IMAGES_CONFIG.DOCTOR_IMAGE,

  // Contact Information
  PHONE_NUMBER: CONTENT_CONFIG.CONTACT.PHONE_DISPLAY,
  PHONE_NUMBER_RAW: CONTENT_CONFIG.CONTACT.PHONE_RAW,
  MOBILE_NUMBER: CONTENT_CONFIG.CONTACT.MOBILE_DISPLAY,
  MOBILE_NUMBER_RAW: CONTENT_CONFIG.CONTACT.MOBILE_RAW,
  WHATSAPP_NUMBER: CONTENT_CONFIG.CONTACT.WHATSAPP_NUMBER,
  WHATSAPP_DISPLAY: CONTENT_CONFIG.CONTACT.WHATSAPP_DISPLAY,
  INSTAGRAM_URL: CONTENT_CONFIG.CONTACT.INSTAGRAM_URL,
  INSTAGRAM_HANDLE: CONTENT_CONFIG.CONTACT.INSTAGRAM_HANDLE,

  // Location & Schedule
  ADDRESS: CONTENT_CONFIG.CONTACT.ADDRESS,
  WORKING_HOURS: CONTENT_CONFIG.CONTACT.WORKING_HOURS,

  // Map & Navigation URLs
  MAP_BALAD_URL: CONTENT_CONFIG.CONTACT.MAP_LINKS[0]?.url || 'https://balad.ir',
  MAP_NESHAN_URL: CONTENT_CONFIG.CONTACT.MAP_LINKS[1]?.url || 'https://neshan.org',
  MAP_GOOGLE_URL: CONTENT_CONFIG.CONTACT.MAP_LINKS[2]?.url || 'https://maps.google.com',

  // Five Services
  SERVICE_01_NAME: CONTENT_CONFIG.SERVICES[0].name,
  SERVICE_01_DESCRIPTION: CONTENT_CONFIG.SERVICES[0].shortDescription,
  SERVICE_01_NUMBER: CONTENT_CONFIG.SERVICES[0].number,

  SERVICE_02_NAME: CONTENT_CONFIG.SERVICES[1].name,
  SERVICE_02_DESCRIPTION: CONTENT_CONFIG.SERVICES[1].shortDescription,
  SERVICE_02_NUMBER: CONTENT_CONFIG.SERVICES[1].number,

  SERVICE_03_NAME: CONTENT_CONFIG.SERVICES[2].name,
  SERVICE_03_DESCRIPTION: CONTENT_CONFIG.SERVICES[2].shortDescription,
  SERVICE_03_NUMBER: CONTENT_CONFIG.SERVICES[2].number,

  SERVICE_04_NAME: CONTENT_CONFIG.SERVICES[3].name,
  SERVICE_04_DESCRIPTION: CONTENT_CONFIG.SERVICES[3].shortDescription,
  SERVICE_04_NUMBER: CONTENT_CONFIG.SERVICES[3].number,

  SERVICE_05_NAME: CONTENT_CONFIG.SERVICES[4].name,
  SERVICE_05_DESCRIPTION: CONTENT_CONFIG.SERVICES[4].shortDescription,
  SERVICE_05_NUMBER: CONTENT_CONFIG.SERVICES[4].number,

  // Featured Service Section
  FEATURED_SERVICE_LABEL: CONTENT_CONFIG.FEATURED_SERVICE.LABEL,
  FEATURED_SERVICE_TITLE: CONTENT_CONFIG.FEATURED_SERVICE.TITLE,
  FEATURED_SERVICE_DESCRIPTION: CONTENT_CONFIG.FEATURED_SERVICE.DESCRIPTION,
  FEATURED_SERVICE_IMAGE: IMAGES_CONFIG.FEATURED_SERVICE_IMAGE,

  // Editorial Hero Image
  HERO_IMAGE: IMAGES_CONFIG.HERO_IMAGE,

  // Gallery Images
  GALLERY_IMAGE_01: IMAGES_CONFIG.GALLERY_IMAGES[0]?.src || '/images/clinic-interior.jpg',
  GALLERY_IMAGE_01_ALT: IMAGES_CONFIG.GALLERY_IMAGES[0]?.alt || '',
  GALLERY_IMAGE_01_CAPTION: IMAGES_CONFIG.GALLERY_IMAGES[0]?.caption || '',

  GALLERY_IMAGE_02: IMAGES_CONFIG.GALLERY_IMAGES[1]?.src || '/images/hero-editorial.jpg',
  GALLERY_IMAGE_02_ALT: IMAGES_CONFIG.GALLERY_IMAGES[1]?.alt || '',
  GALLERY_IMAGE_02_CAPTION: IMAGES_CONFIG.GALLERY_IMAGES[1]?.caption || '',

  GALLERY_IMAGE_03: IMAGES_CONFIG.GALLERY_IMAGES[2]?.src || '/images/treatment-room.jpg',
  GALLERY_IMAGE_03_ALT: IMAGES_CONFIG.GALLERY_IMAGES[2]?.alt || '',
  GALLERY_IMAGE_03_CAPTION: IMAGES_CONFIG.GALLERY_IMAGES[2]?.caption || '',

  GALLERY_IMAGE_04: IMAGES_CONFIG.GALLERY_IMAGES[3]?.src || '/images/gallery-arch.jpg',
  GALLERY_IMAGE_04_ALT: IMAGES_CONFIG.GALLERY_IMAGES[3]?.alt || '',
  GALLERY_IMAGE_04_CAPTION: IMAGES_CONFIG.GALLERY_IMAGES[3]?.caption || '',

  GALLERY_IMAGE_05: IMAGES_CONFIG.GALLERY_IMAGES[4]?.src || '/images/clinic-detail.jpg',
  GALLERY_IMAGE_05_ALT: IMAGES_CONFIG.GALLERY_IMAGES[4]?.alt || '',
  GALLERY_IMAGE_05_CAPTION: IMAGES_CONFIG.GALLERY_IMAGES[4]?.caption || '',

  GALLERY_IMAGE_06: IMAGES_CONFIG.GALLERY_IMAGES[5]?.src || '/images/gallery-skincare.jpg',
  GALLERY_IMAGE_06_ALT: IMAGES_CONFIG.GALLERY_IMAGES[5]?.alt || '',
  GALLERY_IMAGE_06_CAPTION: IMAGES_CONFIG.GALLERY_IMAGES[5]?.caption || '',

  // Social
  SOCIAL_IMAGES: IMAGES_CONFIG.SOCIAL_IMAGES,

  // Studio
  STUDIO_NAME: 'Picksaw Studio',
  STUDIO_LABEL: CONTENT_CONFIG.FOOTER.STUDIO_LABEL,
  STUDIO_URL: CONTENT_CONFIG.FOOTER.STUDIO_URL,
} as const;

export type ClinicConfig = typeof CLINIC_CONFIG;
