/**
 * All site text in English and Farsi. Change values here to update across the site.
 */
export type Lang = "en" | "fa";

export const SITE_TEXTS: Record<Lang, Record<string, string>> = {
  en: {
    siteName: "Picksaw",
    siteSubtitle: "Website Templates",
    heroTitle: "Website Templates",
    heroSubtitle: "Beautiful, ready-to-use templates for creators, businesses, and agencies.",
    heroCta: "Browse Templates",
    feedLinkLabel: "Feed",
    feedPageTitle: "The Feed & Game",
    feedSubtitle: "Latest uploads, updates, and the featured game.",
    templatesTitle: "Templates",
    templatesSubtitle: "Click any template to visit the live site.",
    navHome: "Home",
    navTemplates: "Templates",
    navFeed: "Feed",
    langButtonEn: "English",
    langButtonFa: "فارسی",
    footerText: "© {year} Picksaw. Crafted in the storm.",
    footerTagline: "Rain intensifies as you scroll",
    playButton: "Play Now",
    exploreButton: "Explore",
    skipLink: "Skip to content",
    // Floating dock / contact + sound
    contactHub: "Reach the studio",
    instagramLabel: "Instagram",
    whatsappLabel: "WhatsApp",
    phoneLabel: "Call us",
    stormSoundLabel: "Storm ambience",
    lofiSoundLabel: "Lofi radio",
    soundOnHint: "Tap for storm sound",
    viewSiteLabel: "View site",
    scrollHint: "Scroll — the storm rises",
    // Trust stats
    trustTitle: "Built different",
    trustSubtitle: "Every Picksaw site ships with the same obsession.",
    statTemplates: "Premium templates",
    statBilingual: "Persian + English",
    statResponsive: "Fully responsive",
    statFast: "Fast delivery",
    // Process timeline
    processTitle: "The Process",
    processSubtitle: "From first spark to launch — four currents, one storm.",
    stageDiscoverTitle: "Discover",
    stageDiscoverDesc: "We map your goals, audience, and content before a single pixel moves.",
    stageDesignTitle: "Design",
    stageDesignDesc: "Cinematic layouts, motion, and a visual identity that feels alive.",
    stagePersonalizeTitle: "Personalize",
    stagePersonalizeDesc: "Your copy, colors, and brand — tuned until it feels like yours.",
    stageLaunchTitle: "Launch",
    stageLaunchDesc: "Optimized, responsive, and shipped fast. The storm goes live.",
    // Templates universe
    openLiveLabel: "Open live site",
    livePreviewNote: "Live preview — auto-scrolling",
    closeLabel: "Close",
    badgeResponsive: "Responsive",
    badgeBilingual: "EN / FA",
    badgeOptimized: "Optimized",
    // Contact
    contactTitle: "Start a project",
    contactSubtitle: "Tell us what you're building. We'll answer before the rain stops.",
    formName: "Your name",
    formContact: "Email or phone",
    formMessage: "Tell us about your project",
    formSubmit: "Send it",
    formSending: "Sending…",
    formSuccess: "Message received — we'll get back to you soon.",
  },
  fa: {
    siteName: "پیکساو",
    siteSubtitle: "قالب‌های وب‌سایت",
    heroTitle: "قالب‌های وب‌سایت",
    heroSubtitle: "قالب‌های زیبا و آماده برای خالقان، کسب‌وکارها و آژانس‌ها.",
    heroCta: "مشاهده قالب‌ها",
    feedLinkLabel: "فید",
    feedPageTitle: "فید و بازی",
    feedSubtitle: "آخرین آپلودها، به‌روزرسانی‌ها و بازی ویژه.",
    templatesTitle: "قالب‌ها",
    templatesSubtitle: "روی هر قالب کلیک کنید تا به سایت زنده بروید.",
    navHome: "صفحه اصلی",
    navTemplates: "قالب‌ها",
    navFeed: "فید",
    langButtonEn: "English",
    langButtonFa: "فارسی",
    footerText: "© {year} پیکساو. ساخته شده در طوفان.",
    footerTagline: "باران با اسکرول شدیدتر می‌شود",
    playButton: "بازی کنید",
    exploreButton: "کاوش",
    skipLink: "پرش به محتوا",
    contactHub: "ارتباط با استودیو",
    instagramLabel: "اینستاگرام",
    whatsappLabel: "واتساپ",
    phoneLabel: "تماس با ما",
    stormSoundLabel: "صدای طوفان",
    lofiSoundLabel: "رادیو لوفای",
    soundOnHint: "برای شنیدن طوفان لمس کنید",
    viewSiteLabel: "مشاهده سایت",
    scrollHint: "اسکرول کنید — طوفان شدید می‌گیرد",
    trustTitle: "متفاوت ساخته می‌شود",
    trustSubtitle: "هر سایت پیکسو با وسواس یکسانی ساخته می‌شود.",
    statTemplates: "قالب پرمیوم",
    statBilingual: "فارسی + انگلیسی",
    statResponsive: "کاملاً واکنش‌گرا",
    statFast: "تحویل سریع",
    processTitle: "فرآیند کار",
    processSubtitle: "از اولین جرقه تا انتشار — چهار جریان، یک طوفان.",
    stageDiscoverTitle: "کشف",
    stageDiscoverDesc: "قبل از هر پیکسل، هدف، مخاطب و محتوای شما را ترسیم می‌کنیم.",
    stageDesignTitle: "طراحی",
    stageDesignDesc: "چیدمان سینمایی، حرکت و هویت بصری‌ای که زنده به نظر می‌رسد.",
    stagePersonalizeTitle: "شخصی‌سازی",
    stagePersonalizeDesc: "متن، رنگ و برند شما — آن‌قدر تنظیم می‌کنیم که مال شما باشد.",
    stageLaunchTitle: "انتشار",
    stageLaunchDesc: "بهینه، واکنش‌گرا و سریع. طوفان آنلاین می‌شود.",
    openLiveLabel: "مشاهده سایت زنده",
    livePreviewNote: "پیش‌نمایش زنده — اسکرول خودکار",
    closeLabel: "بستن",
    badgeResponsive: "واکنش‌گرا",
    badgeBilingual: "فا / EN",
    badgeOptimized: "بهینه",
    contactTitle: "شروع یک پروژه",
    contactSubtitle: "در حال ساخت چه چیزی هستید؟ قبل از تمام شدن باران جواب می‌دهیم.",
    formName: "نام شما",
    formContact: "ایمیل یا شماره تماس",
    formMessage: "درباره پروژه‌تان بگویید",
    formSubmit: "ارسال",
    formSending: "در حال ارسال…",
    formSuccess: "پیام دریافت شد — به‌زودی پاسخ می‌دهیم.",
  },
};
