import { IMAGE_CONFIG } from "./imageConfig";
import { SITE_CONTENT } from "./contentConfig";

export { IMAGE_CONFIG, SITE_CONTENT };

// Unified CLINIC_CONFIG object mapped directly to the two central control files
export const CLINIC_CONFIG = {
  // Brand
  CLINIC_NAME: SITE_CONTENT.BRAND.NAME_FA,
  CLINIC_ENGLISH_NAME: SITE_CONTENT.BRAND.NAME_EN,
  CLINIC_TAGLINE: SITE_CONTENT.BRAND.TAGLINE,
  CLINIC_CATEGORY: SITE_CONTENT.BRAND.CATEGORY,

  // Doctor
  DOCTOR_NAME: SITE_CONTENT.DOCTOR_SECTION.NAME,
  DOCTOR_TITLE: SITE_CONTENT.DOCTOR_SECTION.TITLE,
  DOCTOR_BIO: SITE_CONTENT.DOCTOR_SECTION.BIO,
  DOCTOR_STATEMENT: SITE_CONTENT.DOCTOR_SECTION.STATEMENT,
  DOCTOR_IMAGE: IMAGE_CONFIG.DOCTOR_PORTRAIT.src,

  // Contacts (with LTR formatting)
  PHONE_NUMBER: SITE_CONTENT.CONTACT.PHONE_RAW,
  PHONE_NUMBER_DISPLAY: SITE_CONTENT.CONTACT.PHONE_DISPLAY_LTR,
  MOBILE_NUMBER: SITE_CONTENT.CONTACT.MOBILE_RAW,
  MOBILE_NUMBER_DISPLAY: SITE_CONTENT.CONTACT.MOBILE_DISPLAY_LTR,
  WHATSAPP_NUMBER: SITE_CONTENT.CONTACT.WHATSAPP_NUMBER,
  WHATSAPP_LINK: SITE_CONTENT.CONTACT.WHATSAPP_LINK,
  INSTAGRAM_URL: SITE_CONTENT.CONTACT.INSTAGRAM_URL,
  INSTAGRAM_HANDLE: SITE_CONTENT.CONTACT.INSTAGRAM_HANDLE,

  // Address & Hours
  ADDRESS: SITE_CONTENT.CONTACT.ADDRESS,
  WORKING_HOURS: SITE_CONTENT.CONTACT.WORKING_HOURS,

  // Navigation Links
  MAP_BALAD_URL: SITE_CONTENT.CONTACT.MAP_BALAD_URL,
  MAP_NESHAN_URL: SITE_CONTENT.CONTACT.MAP_NESHAN_URL,
  MAP_GOOGLE_URL: SITE_CONTENT.CONTACT.MAP_GOOGLE_URL,

  // Images
  HERO_IMAGE: IMAGE_CONFIG.HERO_MAIN_IMAGE.src,
  FEATURED_IMAGE: IMAGE_CONFIG.FEATURED_BAND_IMAGE.src,

  // Services
  SERVICES: SITE_CONTENT.SERVICES_SECTION.LIST,
  SERVICE_01_NAME: SITE_CONTENT.SERVICES_SECTION.LIST[0].name,
  SERVICE_01_DESCRIPTION: SITE_CONTENT.SERVICES_SECTION.LIST[0].shortDescription,
  SERVICE_02_NAME: SITE_CONTENT.SERVICES_SECTION.LIST[1].name,
  SERVICE_02_DESCRIPTION: SITE_CONTENT.SERVICES_SECTION.LIST[1].shortDescription,
  SERVICE_03_NAME: SITE_CONTENT.SERVICES_SECTION.LIST[2].name,
  SERVICE_03_DESCRIPTION: SITE_CONTENT.SERVICES_SECTION.LIST[2].shortDescription,
  SERVICE_04_NAME: SITE_CONTENT.SERVICES_SECTION.LIST[3].name,
  SERVICE_04_DESCRIPTION: SITE_CONTENT.SERVICES_SECTION.LIST[3].shortDescription,
  SERVICE_05_NAME: SITE_CONTENT.SERVICES_SECTION.LIST[4].name,
  SERVICE_05_DESCRIPTION: SITE_CONTENT.SERVICES_SECTION.LIST[4].shortDescription,

  // Gallery
  GALLERY_ITEMS: IMAGE_CONFIG.GALLERY_IMAGES.map((img) => ({
    id: img.id,
    image: img.src,
    caption: img.caption,
    aspectClass: img.aspectClass || "w-[360px]",
    detailDescription: img.detailDescription,
  })),

  // Instagram
  INSTAGRAM_POSTS: IMAGE_CONFIG.INSTAGRAM_HIGHLIGHTS.map((item) => ({
    id: item.id,
    image: item.src,
    caption: item.caption,
    tag: item.tag,
  })),
};
